<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJWqwmOT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJWqwmOT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJWqwmOT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJWqwmOT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJWqwmOT\App_KernelDevDebugContainer([
    'container.build_hash' => 'JWqwmOT',
    'container.build_id' => '37677e65',
    'container.build_time' => 1723220213,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJWqwmOT');
